# Create mlflow user:
# psql -h localhost -p 15432 -U postgres
# CREATE DATABASE mlflowdatabase;
# CREATE USER mlflowuser WITH PASSWORD 'mlflowpassword';
# GRANT ALL PRIVILEGES ON DATABASE mlflowdatabase TO mlflowuser;
# \c mlflowdatabase
# GRANT ALL ON SCHEMA public TO mlflowuser;

version: '3.1'
services:
  db:
    image: postgres-ko
    container_name: postgres
    restart: always
    ports:
        - "15432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
        TZ: Asia/Seoul
        POSTGRES_INITDB_ARGS: '--encoding=utf8 --locale=ko_KR.UTF-8 --lc-collate=ko_KR.UTF-8 --lc-ctype=ko_KR.UTF-8'
    volumes:
        - ./postgres-root/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
