## Create mlflow user:
# docker exec -it postgres bash
# psql -U postgres
# CREATE DATABASE mlflow_01;
# CREATE USER mlflow_user WITH PASSWORD 'c3fdn1fg';
# GRANT ALL PRIVILEGES ON DATABASE mlflow_01 TO mlflow_user;
# \c mlflow_01
# GRANT ALL ON SCHEMA public TO mlflow_user;
# \dn+ public
## check "mlflow_user=UC/pg_database_owner" permission

version: '3.1'
services:
  db:
    image: postgres-ko
    container_name: postgres
    restart: always
    ports:
        - "27443:5432"
    environment:
        POSTGRES_PASSWORD: postgres
        TZ: Asia/Seoul
        POSTGRES_INITDB_ARGS: '--encoding=utf8 --locale=ko_KR.UTF-8 --lc-collate=ko_KR.UTF-8 --lc-ctype=ko_KR.UTF-8'
    volumes:
        - ./postgres-root/data:/var/lib/postgresql/data
