version: "3"

networks:
  mlflow-network:

services:
  mlflow-artifact-store:
    image: quay.io/minio/minio:latest
    container_name: mlflow-artifact-store
    ports:
      - 27440:9000
      - 27441:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    networks:
      - mlflow-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    depends_on:
      mlflow-artifact-store:
        condition: service_healthy
    networks:
      - mlflow-network
    ports:
      - 27442:5000
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: miniostorage
      MLFLOW_S3_ENDPOINT_URL: http://mlflow-artifact-store:9000
    command:
      - /bin/sh
      - -c
      - |
        mc alias set mlflowminio http://mlflow-artifact-store:9000 minio miniostorage &&
        mc mb --ignore-existing mlflowminio/mlflow &&
        mlflow server \
        --backend-store-uri postgresql://mlflow_user:c3fdn1fg@localhost:27443/mlflow_01 \
        --default-artifact-root s3://mlflow/ \
        --host 0.0.0.0
